--- #YAML:1.0
name: File-Copy-Reliable
version: 0.31
author:
  - Leon Brocard <acme@astray.com>.
abstract: file copying and moving with extra checking
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
